// RouteCoverageTests — QG.1 per-preset audio route-coverage gate.
//
// The failure class this kills: a declared audio route whose primitive silently
// never fires on real music while closeouts claim it works (`vocalsPitchConfidence`
// sat at 0 % for ~5 months). For every shipped sidecar with an `audio_routes`
// manifest, replay the canonical fixture set (real preview clips through the
// production separation + analysis chain — FA #27) and assert, per route, that the
// declared primitive is demonstrably active per its kind's floor.
//
// A red route here is the gate WORKING — surface it as a defect (KNOWN_ISSUES),
// never tune the floors to make it pass (QG.1).
//
// Fixtures: UzumeEngineTests/Fixtures/route_coverage/<track>/{features,stems}.csv,
// generated by FixtureSessionCaptureGenerator (env-gated). Reading three ~1300-row
// CSVs per preset is cheap (no Metal, no DSP) — the suite runs un-gated in the
// normal battery so the gate is always enforced.

import Foundation
import Testing
@testable import Presets
@testable import PresetSessionReplay

struct RouteCoverageTests {

    // MARK: - Per-kind activity floors (QG.1)
    //
    // These constants are the coverage contract. Raise the bar only with evidence;
    // never lower one to make a red route pass (a red route is a defect, not a
    // floor-tuning prompt — QG.1).

    /// `continuous`: the primitive must VARY across every fixture. The floor is
    /// deliberately just above float noise, not an amplitude bar — the gate proves
    /// a route is *alive and responding*, not that it is loud on this material.
    /// A primitive pinned to one value for a whole real-music run is the dead-route
    /// signature (`vocalsPitchConfidence` was exactly constant). Low-amplitude-but-
    /// varying primitives (`high`/`highMid` on bass-heavy material) pass here and are
    /// a fixture-breadth note (QG.1.1 sparse/bright fixtures), not a defect.
    static let continuousStdFloor: Float = 1e-5

    /// `accent`: the primitive must FIRE at least this many times per fixture, where
    /// a firing is a rising crossing above `accentThreshold` (a spike for `*EnergyDev`
    /// / `beatBass`, one wrap per cycle for a phase ramp, one step for a monotone
    /// counter). ≥ 1 on every fixture.
    static let accentMinFiringsPerFixture = 1

    /// A firing is a rising crossing above this level. Calibrated to the *smallest-
    /// range* accent primitive in the corpus — Nacre's `bassAttRel` bass-onset kick,
    /// an attack-RELATIVE deviation that peaks at 0.092 on there_there (softer bass
    /// attacks than the dance/jazz fixtures) while still producing clear transient
    /// events (7 rising crossings above 0.05, sd 0.038). A larger threshold would
    /// mislabel a genuinely-firing route as dead. 0.02 stays well above the 1e-5
    /// float-noise floor: a constant or non-transient primitive scores 0 crossings,
    /// so the dead-route signal is preserved. Do NOT raise this to fail a real route
    /// or lower it to pass a dead one (QG.1).
    static let accentThreshold: Float = 0.02

    /// `gate`: an enable, not a driver (silence gate, confidence gate). The only
    /// failure a gate has is never opening, so the floor is `max ≥ 0.9` on every
    /// fixture — NOT the continuous floor, which asserts variance a correctly-pinned
    /// gate does not have (BUG-088).
    static let gateOpenFloor: Float = 0.9

    /// `structural`: the primitive (section index) must take ≥ 2 distinct values on
    /// AT LEAST ONE fixture — i.e. the canonical set must contain a section boundary
    /// the route can respond to. If no fixture has one, that is a documented fixture
    /// gap (QG.1.1), reported distinctly from a genuine dead route.
    static let structuralMinDistinctValues = 2

    /// FTR.25 — columns that POSTDATE the committed fixtures.
    ///
    /// The fixtures are recorded CSVs with no audio beside them, so a column added to
    /// `FeatureVector` after they were captured cannot be back-filled from them. Such a route is
    /// reported as a fixture gap rather than failing the gate — the policy QG.1.1 already
    /// applies to coverage the fixtures cannot reach.
    ///
    /// ⚠ **REGENERATION WAS TRIED FIRST AND IS BLOCKED ON A SEPARATE FINDING.**
    /// `FixtureSessionCaptureGenerator` still runs (18 s, three clips) and its output DOES carry
    /// the column live on all three tracks (nonzero 80–100 %, sd 0.17–0.35), and with it
    /// installed this gate reads **209 routes / 21 presets, 0 red**. But the regenerated CSVs
    /// differ from the committed ones on EVERY row, and that reds three gates belonging to other
    /// presets — `MeniscusStemDropsTests` (so_what), `WitchlightPathTests` (all three; Witchlight
    /// is CERTIFIED). Either the pipeline's output has moved since the fixtures were captured at
    /// QG.1.3, or the generator is not deterministic. Re-baselining a certified preset's gate as
    /// a side effect of an unrelated increment is not a call to make quietly, so the fixtures
    /// stay as committed and the finding is filed (BUG-090).
    ///
    /// ⚠ THIS SET MUST SHRINK, NEVER GROW QUIETLY. Each entry is a route the gate is NOT
    /// checking. An entry added to turn a red gate green is the floor-tuning move QG.1 exists to
    /// prevent — the gate stays red instead.
    /// BUG-090 resolved 2026-08-17: the fixtures were regenerated, so every column added since
    /// QG.1.3 is now present and route-coverable. Empty is the healthy state — a name here means
    /// a route is UNVERIFIED, so add one only alongside a filed reason to regenerate.
    /// PR.20 — `track_hue_anchor01` was added after the route-coverage fixtures were
    /// captured, so it is absent from all three. Listing it here makes the gate print a
    /// FIXTURE GAP every run instead of failing on a route that is genuinely wired; it does
    /// NOT verify the route. The anchor is also constant within any one track by
    /// construction, so re-capturing a single fixture would still not exercise it — the
    /// property that matters (different tracks land on different anchors) is covered by
    /// `TrackHueAnchorTests.anchorsSpreadAcrossTracks` instead.
    static let columnsPostdatingFixtures: Set<String> = ["track_hue_anchor01"]

    // MARK: - Fixtures

    private static let fixtureTracks = ["love_rehab", "so_what", "there_there"]

    private static func fixtureDirectories() throws -> [(name: String, url: URL)] {
        let base = try #require(
            Bundle.module.url(forResource: "route_coverage", withExtension: nil),
            "route_coverage fixtures not bundled — check Package.swift resources")
        return fixtureTracks.map { ($0, base.appendingPathComponent($0)) }
    }

    // MARK: - The gate

    @Test("Every declared audio route fires on the canonical fixtures (QG.1)")
    func declaredRoutesFireOnRealMusic() throws {
        let shadersURL = try #require(PresetLoader.bundledShadersURL,
            "Shaders resource not found via PresetLoader.bundledShadersURL")
        let jsonFiles = try FileManager.default.contentsOfDirectory(
            at: shadersURL, includingPropertiesForKeys: nil, options: [.skipsHiddenFiles]
        ).filter { $0.pathExtension == "json" }

        // Load each fixture's column series once.
        var series: [(name: String, cols: SessionColumnSeries)] = []
        for (name, url) in try Self.fixtureDirectories() {
            series.append((name, try SessionColumnSeries.load(directory: url)))
        }

        let decoder = JSONDecoder()
        var failures: [String] = []
        var routeCount = 0
        var presetCount = 0

        for jsonURL in jsonFiles.sorted(by: { $0.lastPathComponent < $1.lastPathComponent }) {
            let descriptor = try decoder.decode(PresetDescriptor.self,
                                                from: try Data(contentsOf: jsonURL))
            guard !descriptor.audioRoutes.isEmpty else { continue }
            presetCount += 1
            for route in descriptor.audioRoutes {
                routeCount += 1
                if let fail = Self.evaluate(route: route, in: series, preset: descriptor.name) {
                    failures.append(fail)
                }
            }
        }

        print("RouteCoverageTests: \(routeCount) routes across \(presetCount) presets, "
              + "\(Self.fixtureTracks.count) fixtures — \(failures.count) red")
        let report = failures.joined(separator: "\n")
        #expect(failures.isEmpty,
                "Route-coverage gate red (a declared route's primitive did not fire — file as a route defect in KNOWN_ISSUES, do NOT tune the floor):\n\(report)")
    }

    // MARK: - Per-route evaluation

    /// Returns a failure description, or nil if the route clears its kind's floor.
    private static func evaluate(route: PresetDescriptor.AudioRoute,
                                 in series: [(name: String, cols: SessionColumnSeries)],
                                 preset: String) -> String? {
        guard let mapping = AudioRoutePrimitives.map[route.primitive] else {
            return "\(preset)/\(route.route): primitive '\(route.primitive)' not in the recordable map"
        }
        // Resolve the per-frame series on each fixture (scaled, nils dropped).
        var perFixture: [(name: String, values: [Float])] = []
        for (name, cols) in series {
            guard let raw = cols.floatSeries(mapping.column) else {
                if columnsPostdatingFixtures.contains(mapping.column) {
                    // FIXTURE GAP, not a dead route. Printed every run so it cannot go invisible.
                    print("[route-coverage] FIXTURE GAP \(preset)/\(route.route): "
                          + "'\(mapping.column)' postdates \(name); route UNVERIFIED here")
                    return nil
                }
                return "\(preset)/\(route.route): column '\(mapping.column)' absent from \(name) — not recorded"
            }
            perFixture.append((name, raw.compactMap { $0 }.map { $0 * mapping.scale }))
        }

        switch route.kind {
        case .continuous:
            for (name, v) in perFixture where stddev(v) <= continuousStdFloor {
                return "\(preset)/\(route.route) [\(route.primitive), continuous]: "
                    + "constant on \(name) (stddev \(fmt(stddev(v))) ≤ floor)"
            }
        case .accent:
            for (name, v) in perFixture {
                let firings = risingCrossings(v, threshold: accentThreshold)
                if firings < accentMinFiringsPerFixture {
                    return "\(preset)/\(route.route) [\(route.primitive), accent]: "
                        + "\(firings) firings on \(name) (need ≥ \(accentMinFiringsPerFixture))"
                }
            }
        case .gate:
            for (name, v) in perFixture {
                let peak = v.max() ?? 0
                if peak < gateOpenFloor {
                    return "\(preset)/\(route.route) [\(route.primitive), gate]: "
                        + "never opens on \(name) (peak \(fmt(peak)) < \(gateOpenFloor)) — "
                        + "the visual it enables is suppressed for the whole fixture"
                }
            }
        case .structural:
            let anyBoundary = perFixture.contains { distinctCount($0.values) >= structuralMinDistinctValues }
            if !anyBoundary {
                return "\(preset)/\(route.route) [\(route.primitive), structural]: "
                    + "no fixture contains a section boundary (all constant) — "
                    + "fixture gap (QG.1.1) or dead route"
            }
        }
        return nil
    }

    // MARK: - Activity metrics

    private static func stddev(_ v: [Float]) -> Float {
        guard v.count > 1 else { return 0 }
        let mean = v.reduce(0, +) / Float(v.count)
        let variance = v.reduce(0) { $0 + ($1 - mean) * ($1 - mean) } / Float(v.count)
        return variance.squareRoot()
    }

    /// Count rising crossings above `threshold` (value goes from ≤ threshold to >
    /// threshold). Works for spiky (`*EnergyDev`), binary (`beatBass`), sawtooth
    /// (phase ramps — one crossing per cycle), and monotone (`pulseBeatIndex`) alike.
    private static func risingCrossings(_ v: [Float], threshold: Float) -> Int {
        var count = 0
        var prevAbove = false
        for x in v {
            let above = x > threshold
            if above && !prevAbove { count += 1 }
            prevAbove = above
        }
        return count
    }

    private static func distinctCount(_ v: [Float]) -> Int {
        Set(v.map { ($0 * 1000).rounded() }).count
    }

    private static func fmt(_ x: Float) -> String { String(format: "%.2e", x) }
}
