#!/usr/bin/env python3
"""NRG.2 (D-259): calibrate the 1–10 energy scale on the library.

Input: `<out>.curves.jsonl` from `CorpusCensusRunner --energy` (per-second loudness dB + activity for
whole tracks, produced by the production `analyzeMIR`). Output: `tools/data/energy_scale.json`:

  loud_q, act_q  — 101 library quantiles of per-second loudness and activity (rank tables)
  score_q        — 11 library deciles of the per-second score (edges of levels 1..10)

Per-second score = mean of the second's library rank in loudness and in activity. Either alone
carries mastering bias (loudness most); averaging the two ranks tempers it. Level = the decile of the
score, so each level holds a tenth of the library's seconds.

Usage:
  python3 tools/energy_calibration.py CURVES.jsonl [--out tools/data/energy_scale.json]
                                                   [--swift UzumeEngine/Sources/Session/EnergyScale+Table.swift]
                                                   [--show OTHER.curves.jsonl]
"""
import argparse, bisect, json, os, statistics


def load(path):
    rows = {}
    for line in open(path):
        line = line.strip()
        if line:
            r = json.loads(line)
            rows[r["relpath"]] = r          # duplicates from a resumed run collapse to one
    return list(rows.values())


def quantiles(values, n):
    s = sorted(values)
    return [s[min(len(s) - 1, round(i / (n - 1) * (len(s) - 1)))] for i in range(n)]


def rank(q, x):
    """Library rank of x in [0, 1] by linear interpolation in the quantile table q."""
    i = bisect.bisect_left(q, x)
    if i <= 0:
        return 0.0
    if i >= len(q):
        return 1.0
    lo, hi = q[i - 1], q[i]
    frac = 0.0 if hi == lo else (x - lo) / (hi - lo)
    return (i - 1 + frac) / (len(q) - 1)


def level(scale, loud, act):
    score = 0.5 * rank(scale["loud_q"], loud) + 0.5 * rank(scale["act_q"], act)
    return min(10, max(1, bisect.bisect_right(scale["score_q"][1:-1], score) + 1))


def smooth(values, half=5):
    """Centred ±half-second running median: a section's level, not second-to-second jitter."""
    return [sorted(values[max(0, i - half):i + half + 1])[len(values[max(0, i - half):i + half + 1]) // 2]
            for i in range(len(values))]                     # upper median, as EnergyCurve.runningMedian


def readout(scale, curve):
    """'n' for a steady song, 'lo → hi' when its 10th–90th percentile section levels differ by more than one."""
    keep = [i for i, l in enumerate(curve["loud"]) if l > -90]                       # skip digital silence
    loud, act = smooth([curve["loud"][i] for i in keep]), smooth([curve["act"][i] for i in keep])
    lv = sorted(level(scale, l, a) for l, a in zip(loud, act))
    if not lv:
        return "—"
    lo, hi = lv[int(0.1 * (len(lv) - 1))], lv[int(0.9 * (len(lv) - 1))]
    return str(lv[int(0.5 * (len(lv) - 1))]) if hi - lo <= 1 else f"{lo} → {hi}"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("curves")
    ap.add_argument("--out", default=os.path.join(os.path.dirname(__file__), "data", "energy_scale.json"))
    ap.add_argument("--swift", help="also write the Swift table (EnergyScale+Table.swift)")
    ap.add_argument("--show", help="print readouts for these curves (e.g. the beta playlist)")
    args = ap.parse_args()

    tracks = load(args.curves)
    loud = [l for t in tracks for l in t["loud"] if l > -90]
    act = [a for t in tracks for l, a in zip(t["loud"], t["act"]) if l > -90]
    scale = {"loud_q": quantiles(loud, 101), "act_q": quantiles(act, 101)}
    scores = [0.5 * rank(scale["loud_q"], l) + 0.5 * rank(scale["act_q"], a) for l, a in zip(loud, act)]
    scale["score_q"] = quantiles(scores, 11)
    scale["source"] = {"tracks": len(tracks), "seconds": len(loud), "curves": os.path.basename(args.curves)}
    json.dump(scale, open(args.out, "w"), indent=1)
    print(f"{len(tracks)} tracks, {len(loud)} seconds → {args.out}")
    if args.swift:
        arr = lambda v: "[\n" + "\n".join("            " + ", ".join(f"{x:.6g}" for x in v[i:i + 8]) + ","
                                          for i in range(0, len(v), 8)) + "\n        ]"
        src = ("// EnergyScale+Table — GENERATED by tools/energy_calibration.py; do not edit by hand.\n"
               f"// Source: {scale['source']['curves']} — {len(tracks)} tracks, {len(loud)} seconds.\n\n"
               "// MARK: - Library table\n\n"
               "extension EnergyScale {\n"
               "    /// The library calibration (NRG.2, D-259); mirrors tools/data/energy_scale.json.\n"
               "    public static let library = EnergyScale(\n"
               f"        loudnessQuantiles: {arr(scale['loud_q'])},\n"
               f"        activityQuantiles: {arr(scale['act_q'])},\n"
               f"        scoreDeciles: {arr(scale['score_q'])}\n    )\n}}\n")
        open(args.swift, "w").write(src)
        print(f"  → {args.swift}")

    for path in [args.show] if args.show else []:
        for t in load(path):
            print(f"  {readout(scale, t):>7}   {os.path.basename(t['relpath'])[:60]}")


if __name__ == "__main__":
    main()
